<div class="festi-user-role-prices festi-content">
    <?php
        $params = array(
            'refresh_completed' => '',
            'refresh_plugin' => '',
            'delete_role' => ''
        );
        $url = $this->getUrl($params);
    ?>
    <form action="<?php echo $url; ?>"  method="post" class="festi-user-role-prices-form">
        <input type="hidden" name="__action" value="save" />
        <?php

        $optionsFieldSetKeys = array(
            'settingsTab'    => 'general',
            'hidingRulesTab' => 'hide',
            'taxesTab' => 'taxes',
        );

        $currentTab = key($this->menuOptions);

        if ($this->hasOptionPageInRequest()) {
            $currentTab = $_GET['tab'];
        }

        foreach ($fieldset as $key => $item) {
            if (array_key_exists('legend', $item)) {
            ?>
                <h2><?php echo $item['legend']; ?></h2>
            <?php
            }

            $display = 'display:none';

            if ($optionsFieldSetKeys[$currentTab] == $key) {
                $display = '';
            };

            ?>
            <fieldset class="festi-user-role-prices-options" style="<?php echo $display; ?>">
                <?php
                $vars = array (
                    'fields' => $item['fields'],
                    'currentValues' => $currentValues
                );

                echo $this->fetch('settings_fields.phtml', $vars);

                ?>
                </fieldset>
        <?php
        }
        ?>
        <div class="festi-user-role-prices-save-button-block">
           <input type="submit"  value="<?php echo __('Save Changes', $this->languageDomain); ?>"  class="festi-user-role-prices-save-button button-primary">
        </div>
    </form>
</div>