<table cellpadding="0" cellspacing="0" id="festi-user-role-taxes">
    <tbody>
    <?php

    if (!isset($currentValue)) {
        $currentValue = array();
    }

    foreach ($roles as $key => $role) {
        ?>
        <tr>
            <th>
                <span><?php echo $role['name'].":"; ?></span>
            </th>
            <td>
                <?php

                $columnKey = 'taxClass';

                if (
                    !array_key_exists($key, $currentValue) ||
                    !array_key_exists($columnKey, $currentValue[$key])
                ) {
                    $value = 0;
                } else {
                    $value = $currentValue[$key][$columnKey];
                }

                $facade = $this->ecommerceFacade;

                $taxClasses = $facade->getTaxClasses();

                $vars = array (
                    'ident' => $ident.'['.$key.']['.$columnKey.']',
                    'item' => array(
                        'values' => $taxClasses
                    ),
                    'currentValue' => $value
                );

                echo $this->fetch('form/input_select.phtml', $vars);

                $columnKey = 'taxType';

                if (
                    !array_key_exists($key, $currentValue) ||
                    !array_key_exists($columnKey, $currentValue[$key])
                ) {
                    $value = 'Default';
                } else {
                    $value = $currentValue[$key][$columnKey];
                }

                $vars = array (
                    'ident' => $ident.'['.$key.']['.$columnKey.']',
                    'item' => array(
                        'values' => array(
                            static::FESTI_DEFAULT_TAX_KEY => __('Default', $this->languageDomain),
                            static::FESTI_EXCLUDE_ALL_TAX_KEY => __(
                                    'Show Price Excluding Tax',
                                    $this->languageDomain
                            ),
                            static::FESTI_EXCLUDE_TAX_IN_SHOP_KEY => __(
                                    'Show Price Excluding Tax in Shop',
                                    $this->languageDomain
                            ),
                            static::FESTI_EXCLUDE_TAX_IN_CART_AND_CHECKOUT_KEY => __(
                                    'Show Price Excluding Tax in Cart and Checkout',
                                    $this->languageDomain
                            )
                        )
                    ),
                    'currentValue' => $value
                );

                echo $this->fetch('form/input_select.phtml', $vars);

                ?>

            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>